language: R
sudo: false
cache: packages
warnings_are_errors: false
branches:
  only:
  - master
  - dev
latex: false
before_install:
- sudo apt-get -y install libmagick++-dev
r_packages:
- covr
after_success:
- Rscript -e 'library(covr); codecov()'
notifications:
  email:
    recipients:
    - andrew@exegetic.biz
    on_success: change
    on_failure: change
env:
  global:
  - secure: O5JdtLYc/dhRvUHtk4vf/eKCPk+9D200oML98+i/gkjK6/gR7qbrFZW7YbIB56s0I7FHGeYk06zu7cMi9swZmcyeQ9Q30hE1oIsAh176Bq/aKqQe3nF9cG1vcaPCsvyr/amnAhFr4fUTWMTSALrAEFUBXV5+lqu9O8ZW3COkuDEeQ8C3QYsbWYoyHxijnp1QN/O9Tbag51Sxzc+J74uuarXSTPgM0qcAbcvIKxgZI5mQFPl6CD64NxUf/DeHQwkMQfK6rV8VCAzKY77nLwNbQpjoMWQpZJIuC48tOwHpNJJoShSS1wRc3s6IyiLQ2mI0DBSkr7Q1INjqz2+lMaNkDX3KMa12PbxFkEQiH0wMUW3nGcREYZfc3eyd4j9cqruUjlE7mj1/XP4JAUCU0UZnox/hxJ8skl7QibtSrtHXZpchPTNHVWFVaKaftMVGZoS+yWIekomJkpSn3W7P6qwWAbKzxYinPeY2xQ+/0bgmY7pkwX/wiOnPneBhB5+wnMo6q1t3INa3ye727pBQwowp7e34piYXdPEy1dStExz9OH5sQRPyZi/PI5bMY8DZozP+6LFN2OsTuHdPlMo58h4WUTNfol89gig6KHm4Z5HFlCMcWMt5iJ7TdjzsY6VviRqOFtSojKPwLemlFSeTnDMzs1LYF72sPmz6DzRIWLujhA0=
  - secure: TPlCwwosFv6jXSkYpGz+YrjfR/UfXtu5CSqB0a4i3LOyXVi1sYbN7eqPjKmBvwswDM0WGRdgbIC9LYzVrbsxuAEgjREE3RdMgu6aGy0Y4mgbSp9Y72NKkbXUW1zOvnN7djdxTrZ1iTOo/9N8LR5Mw6CBonUpzbg6Wj3kyM27FRRVDC8HZq53Cnf4fhAnot/eUjpjVVrXLMGaXU+7WBKR8FZ1/tpwNk+g3VWJoDpAepgJn2ZWoEwZtBcd4uRgPHFt9ZDZiQtmZuKMYdZ06WpMf+WdXUPKRSX9/ThPZtgU6xtNXPSIzKBDR2aMrqbCYeDLG1fDQ5dqv+JMge1o+i2NCH8EGmIqBesTOxCXP0KI27U1+NhTNJD4cdruIknJ3J9SnK12RyXI0tyG8V7FwYP0TNy1BfQuMJ/G4iHQ0TLJptd5FUn3C4Az0fpF6Ol5fgeQGU9Bb6PjpFmNk+3NQYR525qsRjMq6IcyZlNXNfsZz902ZZdznzYvU1CJgaR6Fm3F7r083ozBvh6iN43zRjDIS43OKXorNS5zUuPepeH8LqD1YIszsGMwjG/2zgOujemXBsVcfdPHVaU04c94/5C0/T5fQicseIsbXsR8CpM/gZTxmgb4Xk8EHfO3IAIebis3L9awduvjHrW0dFf7czLlnDQiPxzICG1rLp8a2N1hEEQ=
